export const SHOW_FILES_LOADER = "SHOW_FILES_LOADER"
export const HIDE_FILES_LOADER = "HIDE_FILES_LOADER"

export const FILES_FETCH_SUCCESS = "FILES_FETCH_SUCCESS"
export const FILES_FETCH_FAILURE = "FILES_FETCH_FAILURE"

export const AUTHORIZE_TOKEN_SUCCESS = "AUTHORIZE_TOKEN_SUCCESS"
export const AUTHORIZE_TOKEN_FAILURE = "AUTHORIZE_TOKEN_FAILURE"

export const SET_PATH = "SET_PATH"